garbage_dict = {
    "Disposable fast food box": "Residual Waste",
    "Book paper": "Recyclable Waste",
    "Power bank": "Hazardous Waste",
    "Leftovers": "Household Food Waste",
    "Package": "Recyclable Waste",
    "Trash can": "Residual Waste",
    "Plastic utensils": "Hazardous Waste",
    "Plastic toys": "Recyclable Waste",
    "Plastic clothes hanger": "Recyclable Waste",
    "Big Bones": "Household Food Waste",
    "Dry cell battery": "Hazardous Waste",
    "Express paper bag": "Recyclable Waste",
    "Plug wire": "Recyclable Waste",
    "Old clothes": "Recyclable Waste",
    "Cans": "Recyclable Waste",
    "Pillow": "Residual Waste",
    "Peel and pulp": "Household Food Waste",
    "Plush toys": "Recyclable Waste",
    "Defaced plastic": "Residual Waste",
    "Damaged paper": "Residual Waste",
    "Toiletries": "Residual Waste",
    "Cigarette butts": "Residual Waste",
    "Toothpick": "Residual Waste",
    "Glassware": "Residual Waste",
    "Chopping board": "Residual Waste",
    "Chopsticks": "Residual Waste",
    "Carton carton": "Recyclable Waste",
    "Flowerpot": "Residual Waste",
    "Tea leaves": "Household Food Waste",
    "Caibangcaiye": "Recyclable Waste",
    "Eggshell": "Household Food Waste",
    "Condiment bottle": "Recyclable Waste",
    "Ointment": "Hazardous Waste",
    "Expired medicines": "Hazardous Waste",
    "Wine bottle": "Recyclable Waste",
    "Metal kitchenware": "Recyclable Waste",
    "Metal utensils": "Recyclable Waste",
    "Metal food cans": "Recyclable Waste",
    "Pot": "Recyclable Waste",
    "Ceramic ware": "Residual Waste",
    "Shoes": "Recyclable Waste",
    "Edible oil drum": "Recyclable Waste",
    "Beverage bottles": "Recyclable Waste",
    "Fish bones": "Household Food Waste"
}

